package handler

import(
	"github.com/labstack/echo/v4"
	"hw4/internal/model"
	"hw4/internal/service"
)

type Handler struct {
	service *service.Service
}

func NewHandler(s *service.Service) *Handler {
	return &Handler{service: s}
}

func (h *Handler) GetStudents(c echo.Context) error {
	id := c.Param("id")
	stud, err := h.service.GetStudentByID(id)
	if err != nil {
		return c.JSON(500, map[string]string{"error": err.Error()})
	}	
	return c.JSON(200, stud)
}

func (h *Handler) GetAllSchedule(c echo.Context) error {
	AllSchedule, err := h.service.GetAllSchedule()
	if err != nil {
		return c.JSON(500, map[string]string{"error": err.Error()})
	}
	return c.JSON(200, AllSchedule)
}

func (h *Handler) GetGroupSchedule(c echo.Context) error {
	id := c.Param("id")
	groupSchedule, err := h.service.GetGroupScheduleByID(id)
	if err != nil {
		return c.JSON(500, map[string]string{"error": err.Error()})
	}
	return c.JSON(200, groupSchedule)
}

func (h *Handler) GetSubjectAttendance(c echo.Context) error {
	id := c.Param("id")
	subjectAttendance, err := h.service.GetSubjectAttendance(id)
	if err != nil {
		return c.JSON(500, map[string]string{"error": err.Error()})
	}
	return c.JSON(200, subjectAttendance)
}

func (h *Handler) GetStudentAttendance(c echo.Context) error{
	id := c.Param("id")
	studentAttendance, err := h.service.GetStudentAttendance(id)
	if err != nil {
		return c.JSON(500, map[string]string{"error": err.Error()})
	}
	return c.JSON(200, studentAttendance)
}

func (h *Handler) PostSubjectAttendance (c echo.Context) error{
	var attendance model.Attendance
	if err := c.Bind(&attendance); err != nil {
		return c.JSON(400, map[string]string{"error": "Invalid request payload"})
	}

	// Ensure ID is 0 (will be auto-generated by database)
	attendance.ID = 0

	// Call service to create attendance record
	createdAttendance, err := h.service.PostSubjectAttendance(&attendance)
	if err != nil {
		// Check for validation errors (400) vs server errors (500)
		if err.Error() == "student_id is required" || 
		   err.Error() == "schedule_id is required" || 
		   err.Error() == "date is required" ||
		   err.Error() == "student not found" ||
		   err.Error() == "schedule not found" ||
		   err.Error() == "attendance record already exists for this student, schedule, and date" {
			return c.JSON(400, map[string]string{"error": err.Error()})
		}
		return c.JSON(500, map[string]string{"error": err.Error()})
	}
	
	return c.JSON(201, createdAttendance)
}